sources:
  - name: raw
    database: week8_demo
    schema: raw
    description: "Schema which stores raw tables from ETL"
    tables:
      - name: user_session_channel
        identifier: user_session_channel
      - name: session_timestamp
        identifier: session_timestamp